services:
  mecanopecas-db:
    image: mysql
    volumes:
      - db-mecanopecas:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mecanopecas
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mecanopecas

  npm:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./front-mecanopecas:/usr/src/app
    command: tail -f /dev/null
    ports:
      - "5173:5173"

volumes:
  db-mecanopecas: