services:
  mecanopecas-db:
    image: mysql
    volumes:
      - db-mecanopecas:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mecanopecas
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mecanopecas


volumes:
  db-mecanopecas: