version: '3.8'

services:
  mecanopecas-db:
    image: mysql
    volumes:
      - db-mecanopecas:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mecanopecas
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mecanopecas

  frontend:
    build:
      context: ./front-mecanopecas
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./back-mecanopecas
    ports:
      - "8080:8080"
    depends_on:
      - mecanopecas-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mecanopecas-db:3306/mecanopecas
      SPRING_DATASOURCE_USERNAME: mecanopecas
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db-mecanopecas: